<!--
Copyright 2018 JQueryForm.com
License: http://www.jqueryform.com/license.php

FormID: jqueryform-0a74c0
Date: 2018-02-28 09:58:38
Generated by http://www.jqueryform.com
-->
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="generator" content="jqueryform.com">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

  <title>Place your order here</title>
  

  <!-- Bootstrap -->
 
  

  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  <link href="vendor.css" rel="stylesheet">

<style type="text/css">
body{
  background-color: transparent;
}

.jf-form{
  margin-top: 28px;
}

.jf-form > form{
  margin-bottom: 32px;
}

.jf-option-box{
  display: none;
  margin-left: 8px;
}

.jf-hide{
  display: none;
}

.jf-disabled {
    background-color: #eeeeee;
    opacity: 0.6;
    pointer-events: none;
}

/* 
overwrite bootstrap default margin-left, because the <label> doesn't contain the <input> element.
*/
.checkbox input[type=checkbox], .checkbox-inline input[type=checkbox], .radio input[type=radio], .radio-inline input[type=radio] {
  position: absolute;
  margin-top: 4px \9;
  margin-left: 0px;
}

div.form-group{
  padding: 8px 8px 4px 8px;
}

.mainDescription{
  margin-bottom: 10px;
}

p.description{
  margin:0px;
}

.responsive img{
  width: 100%;
}

p.error, p.validation-error{
  padding: 5px;
}

p.error{
  margin-top: 10px;
  color:#a94442;
}

p.server-error{
  font-weight: bold;
}

div.thumbnail{
  position: relative;
  text-align: center;
}

div.thumbnail.selected p{
  color: #ffffff;
}

div.thumbnail .glyphicon-ok-circle{
  position: absolute;
  top: 16px;
  left: 16px;
  color: #ffffff;
  font-size: 32px;
}

.jf-copyright{color: #888888; display: inline-block; margin: 16px;display:none;}

.form-group.required .control-label:after {
    color: #dd0000;
    content: "*";
    margin-left: 6px;
}

.submit .btn.disabled, .submit .btn[disabled]{
  background: transparent;
  opacity: 0.75;
}

/* for image option with span text */
.checkbox label > span, .radio label > span{
  display: block;
}

.form-group.inline .control-label,
.form-group.col-1 .control-label,
.form-group.col-2 .control-label,
.form-group.col-3 .control-label
{
  display: block;
}

.form-group.inline div.radio,
.form-group.inline div.checkbox{
  display: inline-block;
}

.form-group.col-1 div.radio,
.form-group.col-1 div.checkbox{
  display: block;
}

.form-group.col-2 div.radio,
.form-group.col-2 div.checkbox{
  display: inline-flex;
  width: 48%;
}

.form-group.col-3 div.radio,
.form-group.col-3 div.checkbox{
  display: inline-flex;
  width: 30%;
}

.clearfix:after {
   content: ".";
   visibility: hidden;
   display: block;
   height: 0;
   clear: both;
}

</style>


</head>

<body>


<!-- ----------------------------------------------- -->
<div class="container jf-form">
<form data-licenseKey="" name="jqueryform-0a74c0" id="jqueryform-0a74c0" action='admin.php' method='post' enctype='multipart/form-data' novalidate autocomplete="on">
<input type="hidden" name="method" value="validateForm">
<input type="hidden" id="serverValidationFields" name="serverValidationFields" value="">



<div class="form-group f1 required" data-fid="f1">
  <label class="control-label" for="f1">Your Name</label>

<div class="input-group"><span class="input-group-addon left"><i class="glyphicon glyphicon-user"></i> </span>
<input type="text" class="form-control" id="f1" name="f1" value=""    
    data-rule-required="true"  />
</div>

  
</div>




<div class="form-group f2 required" data-fid="f2">
  <label class="control-label" for="f2">Email</label>

<div class="input-group"><span class="input-group-addon left"><i class="glyphicon glyphicon-envelope"></i> </span>
<input type="email" class="form-control" id="f2" name="f2" value=""   
    data-rule-email="true" 
    data-rule-required="true"  />
</div>
  
</div>




<div class="form-group f4 " data-fid="f4">
  <label class="control-label" for="f4">Phone</label>

<div class="input-group"><span class="input-group-addon left"><i class="glyphicon glyphicon-earphone"></i> </span>
<input type="tel" class="form-control" id="f4" name="f4" value=""   placeholder="xxx-xxx-xxxx" 
    data-rule-pattern="[0-9]{3,4}[ -.]*[0-9]{3,4}[ -.]*[0-9]{4}" data-msg-pattern="Invalid phone number"    /></div>

  
</div>




<div class="form-group f5 " data-fid="f5">
  <label class="control-label" for="f5">Ginger</label>

<div class="checkbox">
  	<input  id="f5_1" name="f5[]"  type="checkbox" value="6 pack" 
     >
  	<label  for="f5_1">
  		6 pack
  	</label>
  </div>

  <div class="checkbox">
  	<input  id="f5_2" name="f5[]"  type="checkbox" value="12 pack"  >
  	<label  for="f5_2">
  		12 pack
  	</label>
  </div>

  <div class="checkbox">
  	<input  id="f5_3" name="f5[]"  type="checkbox" value="24 pack"  >
  	<label  for="f5_3">
  		24 pack
  	</label>
  </div>

  
</div>




<div class="form-group f6 " data-fid="f6">
  <label class="control-label" for="f6">Hibiscus</label>

<div class="checkbox">
  	<input  id="f6_1" name="f6[]"  type="checkbox" value="6 pack" 
     >
  	<label  for="f6_1">
  		6 pack
  	</label>
  </div>

  <div class="checkbox">
  	<input  id="f6_2" name="f6[]"  type="checkbox" value="12 pack"  >
  	<label  for="f6_2">
  		12 pack
  	</label>
  </div>

  <div class="checkbox">
  	<input  id="f6_3" name="f6[]"  type="checkbox" value="24 pack"  >
  	<label  for="f6_3">
  		24 pack
  	</label>
  </div>

  
</div>




<div class="form-group f7 " data-fid="f7">
  <label class="control-label" for="f7">Ginger quantity</label>


<select class="form-control" id="f7" name="f7"   
    >
  <option  value="">- Select -</option>
  <option  value="1">1</option>
  <option  value="2">2</option>
  <option  value="3">3</option>
  <option  value="4">4</option>
  <option  value="5">5</option>
  <option  value="6">6</option>
  <option  value="7">7</option>
  <option  value="8">8</option>
  <option  value="9">9</option>
  <option  value="10">10</option>
  <option  value="11">11</option>
  <option  value="12">12</option>
  <option  value="13">13</option>
  <option  value="14">14</option>
  <option  value="15">15</option>
  <option  value="16">16</option>
  <option  value="17">17</option>
  <option  value="18">18</option>
  <option  value="19">19</option>
  <option  value="20">20</option>
  </select>

  
</div>




<div class="form-group f8 " data-fid="f8">
  <label class="control-label" for="f8">Hibiscus quantity</label>


<select class="form-control" id="f8" name="f8"   
    >
  <option  value="">- Select -</option>
  <option  value="1">1</option>
  <option  value="2">2</option>
  <option  value="3">3</option>
  <option  value="4">4</option>
  <option  value="5">5</option>
  <option  value="6">6</option>
  <option  value="7">7</option>
  <option  value="8">8</option>
  <option  value="9">9</option>
  <option  value="10">10</option>
  <option  value="11">11</option>
  <option  value="12">12</option>
  <option  value="13">13</option>
  <option  value="14">14</option>
  <option  value="15">15</option>
  <option  value="16">16</option>
  <option  value="17">17</option>
  <option  value="18">18</option>
  <option  value="19">19</option>
  <option  value="20">20</option>
  </select>

  
</div>




<div class="form-group gaddress f9 required" data-fid="f9">
    <label class="control-label">Shipping address</label>

    <div class="form-group addressLine1">
        <label class="control-label sr-only" for="f9_addressLine1">Address Line1</label>
        <input type="text" class="form-control gaddress-autocomplete" data-gaddress-types="street_number route" data-gaddress-name="long_name" id="f9_addressLine1" name="f9_addressLine1" value=""  aria-describedby="f9_addressLine1-help-block" placeholder="1234 Main St." 
    data-rule-required="true" data-msg-required="This field is required."  />
        <p id="f9_addressLine1-help-block" class="description sr-only">Street address, P.O. box, company name, c/o</p> 
    </div>


    <div class="form-group city">
        <label class="control-label sr-only" for="f9_city">City</label>
        <input type="text" class="form-control" data-gaddress-types="locality" data-gaddress-name="long_name"  id="f9_city" name="f9_city" value=""  aria-describedby="f9_city-help-block" placeholder="City" 
    data-rule-required="true" data-msg-required="This field is required."  />
        <p id="f9_city-help-block" class="description sr-only">City</p>
    </div>

    <div class="form-group state">
        <label class="control-label sr-only" for="f9_state">State / Province / Region</label>
        <input type="text" class="form-control" data-gaddress-types="administrative_area_level_1" data-gaddress-name="long_name"  id="f9_state" name="f9_state" value=""  aria-describedby="f9_state-help-block" placeholder="State / Province / Region" 
    data-rule-required="true" data-msg-required="This field is required."   />
        <p id="f9_state-help-block" class="description sr-only">State / Province / Region</p>
    </div>

    <div class="form-group postalCode">
        <label class="control-label sr-only" for="f9_postalCode">Postal / Zip Code</label>
        <input type="text" class="form-control" data-gaddress-types="postal_code" data-gaddress-name="long_name" id="f9_postalCode" name="f9_postalCode" value=""  aria-describedby="f9_postalCode-help-block" placeholder="Postal / Zip Code" 
    data-rule-required="true" data-msg-required="This field is required."  />
        <p id="f9_postalCode-help-block" class="description sr-only">Postal / Zip Code</p> 
    </div>

    <div class="form-group country">
        <label class="control-label sr-only" for="f9_country">Country</label>
        <input type="text" class="form-control" data-gaddress-types="country" data-gaddress-name="long_name" id="f9_country" name="f9_country" value=""  aria-describedby="f9_country-help-block" placeholder="Country" 
    data-rule-required="true" data-msg-required="This field is required."  />
        <p id="f9_country-help-block" class="description sr-only">Country</p>
    </div>
    
    <div class='mq-indicator'></div>

</div>




<div class="form-group gaddress f10 required" data-fid="f10">
    <label class="control-label">Billing address</label>

    <div class="form-group addressLine1">
        <label class="control-label sr-only" for="f10_addressLine1">Address Line1</label>
        <input type="text" class="form-control gaddress-autocomplete" data-gaddress-types="street_number route" data-gaddress-name="long_name" id="f10_addressLine1" name="f10_addressLine1" value=""  aria-describedby="f10_addressLine1-help-block" placeholder="1234 Main St." 
    data-rule-required="true" data-msg-required="This field is required."  />
        <p id="f10_addressLine1-help-block" class="description sr-only">Street address, P.O. box, company name, c/o</p> 
    </div>


    <div class="form-group city">
        <label class="control-label sr-only" for="f10_city">City</label>
        <input type="text" class="form-control" data-gaddress-types="locality" data-gaddress-name="long_name"  id="f10_city" name="f10_city" value=""  aria-describedby="f10_city-help-block" placeholder="City" 
    data-rule-required="true" data-msg-required="This field is required."  />
        <p id="f10_city-help-block" class="description sr-only">City</p>
    </div>

    <div class="form-group state">
        <label class="control-label sr-only" for="f10_state">State / Province / Region</label>
        <input type="text" class="form-control" data-gaddress-types="administrative_area_level_1" data-gaddress-name="long_name"  id="f10_state" name="f10_state" value=""  aria-describedby="f10_state-help-block" placeholder="State / Province / Region" 
    data-rule-required="true" data-msg-required="This field is required."   />
        <p id="f10_state-help-block" class="description sr-only">State / Province / Region</p>
    </div>

    <div class="form-group postalCode">
        <label class="control-label sr-only" for="f10_postalCode">Postal / Zip Code</label>
        <input type="text" class="form-control" data-gaddress-types="postal_code" data-gaddress-name="long_name" id="f10_postalCode" name="f10_postalCode" value=""  aria-describedby="f10_postalCode-help-block" placeholder="Postal / Zip Code" 
    data-rule-required="true" data-msg-required="This field is required."  />
        <p id="f10_postalCode-help-block" class="description sr-only">Postal / Zip Code</p> 
    </div>

    <div class="form-group country">
        <label class="control-label sr-only" for="f10_country">Country</label>
        <input type="text" class="form-control" data-gaddress-types="country" data-gaddress-name="long_name" id="f10_country" name="f10_country" value=""  aria-describedby="f10_country-help-block" placeholder="Country" 
    data-rule-required="true" data-msg-required="This field is required."  />
        <p id="f10_country-help-block" class="description sr-only">Country</p>
    </div>
    
    <div class='mq-indicator'></div>

</div>





<div class='form-group recaptcha'>
  <script type="text/javascript">
  	function renderReCaptcha(){
  		var jfKey = '6LdopwYTAAAAABunoQoWr5mZGVpVSmTFumNM8ZfO', // when form loaded from jqueryform.com
  		realKey = '6LfIdkkUAAAAAKuouLJUB003NDHLBqiAJkbW6qdX',
  		theme = 'light',
  		key = -1 !== location.href.indexOf('jqueryform.com/') ? jfKey : realKey;
  		grecaptcha.render( document.getElementById('g-recaptcha'), {
          'sitekey' : key,
          'theme' : theme
        });
  	};
  </script>
  <script src="https://www.google.com/recaptcha/api.js?hl=&onload=renderReCaptcha&render=explicit" async defer></script>
  <div id='g-recaptcha' class='g-recaptcha col_field' data-theme='light' data-sitekey='6LfIdkkUAAAAAKuouLJUB003NDHLBqiAJkbW6qdX'></div>
</div>





<div class="form-group submit f0 " data-fid="f0" style="position: relative;">
  <label class="control-label sr-only" for="f0" style="display: block;">Submit Button</label>

  <div class="progress" style="display: none; z-index: -1; position: absolute;">
    <div class="progress-bar progress-bar-striped active" role="progressbar" style="width:100%">
    </div>
  </div>

  <button type="submit" class="btn btn-primary btn-lg" style="z-index: 1;">
  		Submit
  </button>

</div><div class="clearfix"></div>

<div class="submit">
  <p class="error bg-warning" style="display:none;">
    Please check the required fields.  </p>
</div>

<div class="clearfix"></div>


</form>

<a href="http://www.jqueryform.com" target="_blank" class="jf-copyright">Powered by jqueryform.com</a>
</div>

<div class="container jf-thankyou" style="display:none;" data-redirect="http%3A%2F%2Fklcuisine.com%2Fstore%2Fthankyou.php" data-seconds="10">
  <h3>Your form has been submitted. Thank You!</h3>
</div>
<!-- ----------------------------------------------- -->


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.0/js/bootstrap-datepicker.min.js"></script>
<script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.13.1/jquery.validate.min.js"></script>
<script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.13.1/additional-methods.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-scrollTo/2.1.0/jquery.scrollTo.min.js"></script>
<script src="vendor.js" ></script>

<script src="jqueryform.com.min.js?ver=v2.1.0&id=jqueryform-0a74c0" ></script>




<!-- [ Start: iCheck support ] ---------------------------------- -->
<link href="https://cdn.jsdelivr.net/icheck/1.0.2/skins/flat/_all.min.css" rel="stylesheet">
<style type="text/css">
/* overwrite bootstrap styles */
.checkbox input[type=checkbox], .checkbox-inline input[type=checkbox], .radio input[type=radio], .radio-inline input[type=radio] {
    position: relative;
    margin-top: 0px;
    margin-left: 2px;
}

.checkbox label, .radio label {
   padding-left: 4px;
}

</style>

<script src="https://cdn.jsdelivr.net/icheck/1.0.2/icheck.min.js"></script>
<script type="text/javascript">


;(function ($, undefined)
{

var checkers = '.icheckbox_flat, .iradio_flat';

function initICheck( $input ){
  $input.iCheck({
	    checkboxClass: 'icheckbox_flat',
	    radioClass: 'iradio_flat'
  }).on('ifClicked', function(e){
    setTimeout( function(){
      $(e.target).valid();
      $(e.target).trigger('change').trigger('handleOptionBox');
    }, 250);
  });
}; // func

//$('.jf-form .checkbox, .jf-form .radio')
$('.jf-form input[type="checkbox"], .jf-form input[type="radio"]').each( function( i, e ){
    var $input = $(e), $div = $input.closest('.checkbox,.radio'), hasImg = $div.find('label > img').length;
    if( hasImg ){

        $input.css({ 'opacity': '0', 'position': 'absolute', 'left': '-1000px', 'right': '-1000px'} );

    }else{

        initICheck( $input );

        // IE11 and under, the table-cell makes the checkboxes/radio buttons not clickable
        var isWin = navigator.platform.indexOf('Win') > -1,
            isEdge = navigator.userAgent.indexOf('Edge/') > -1,
            noTableCell = isWin && !isEdge;
        if( !noTableCell ){
          $div.find('label').css( { display: 'table-cell' } );
          $(checkers).css( { display: 'table-cell' } );
        };

    };
});

})(jQuery);

</script>
<!-- [ End: iCheck support ] ---------------------------------- -->


<!-- [ Start: Select2 support ] ---------------------------------- -->
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/css/select2.min.css">
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/js/select2.full.min.js"></script>
<style type="text/css">
.select2-hidden-accessible{
	opacity: 0;
    width:1% !important;
}
.select2-container .select2-selection--single{
  height: 34px;
  padding-top: 2px;
  box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
  border: 1px solid #ccc;
}
.select2-container--default .select2-selection--single .select2-selection__arrow{
  top: 4px;
}
</style>
<script type="text/javascript">
;(function(){
	
	function templateResult (obj) {
	  if (!obj.id) { return obj.text; }

	  var img = $(obj.element).data('imgSrc');
	  if( img ){
	    return $( '<span><img src="' + img + '" class="img-flag" /> ' + obj.text + '</span>' );
	  };

	  return obj.text;
	};
	 
	$(".jf-form select").css('width', '100%'); // make it responsive
	$(".jf-form select").select2({
	  templateResult: templateResult
	}).change( function(e){
	  $(e.target).valid();
	});

})();
</script>
<!-- [ End: Select2 support ] ---------------------------------- -->



<style>
.gaddress .form-group {
  padding-left: 0px;
}

.gaddress .mq-indicator{
  display:none;
}

@media only screen and (min-width : 767px) {
    .gaddress .mq-indicator{
      display:block;
      height:1px;
      margin-top: -19px;
    }

    .gaddress .form-group.city,
    .gaddress .form-group.state,
    .gaddress .form-group.postalCode,
    .gaddress .form-group.country
    {
        display: inline-block;
        width: 48%;
        vertical-align: top;    
    }

}
</style>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDtXpn6gUreNd7lbpKUKPEgt6oXmVl5BSo&libraries=places"></script>

<script type="text/javascript">
;(function ($, undefined)
{



var alignRight = function(){

    var docW = $(document).width();

    $('.gaddress').each( function(){

        var $fields = $(this).find('.city,.state,.postalCode,.country'), idx = 0, w = 0;
        $fields.each( function(i, e){
            w = parseInt( $(e).width() );
            if( 1 == idx % 2 && docW >= 768 ){
                $(e).css( { float: 'right' } );
            }else{
                $(e).css( { float: 'none' } );
            };
            idx ++;
        }); // each

    }); // each

}; // alignRight

alignRight();
$(window).resize( alignRight );
    


// $input is a jQuery input object
var gaComplete = function( $input ){
  var autocomplete,


  initAutocomplete = function () {
    $input.focus( geolocate );
    var options = {
        
        types: ['address']
    };
    autocomplete = new google.maps.places.Autocomplete(
        $input.get(0),
        options
    );
    autocomplete.addListener('place_changed', fillInAddress);
  }, // initAutocomplete


  fillInAddress = function () {
    // Get the place details from the autocomplete object.
    var place = autocomplete.getPlace();
    $input.closest('.gaddress').find('[data-gaddress-types]').each( function(){
      
      var $t = $(this), 
      types  = $t.data('gaddress-types').replace(/\s+/g,' '),
      orType = types.indexOf(',') !== -1 ,
      types  = types.split( orType ? ',' : ' ' ), 
      name   = $t.data('gaddress-name'),
      values = [];

      if(  !(name == 'long_name' || name == 'short_name') ){
        name = 'long_name';
      };

      for (var i = 0; i < place.address_components.length; i++) {
        var address = place.address_components[i];
        
        for (var j = 0; j < types.length; j++) {
          if( -1 !== $.inArray( types[j], address.types ) ){
            values.push( address[ name ] );
            if( orType ) break; // found one of the defined types
          };
        }; // for j
        
        if( orType ) break; // found one of the defined types
      };// for i

      $t.val( values.join(' ') ).valid();
      
    });
  }, // fillInAddress


  geolocate = function () {
    if (!navigator.geolocation)
      return;

    navigator.geolocation.getCurrentPosition(function(position) {
      var geolocation = {
        lat: position.coords.latitude,
        lng: position.coords.longitude
      };
      var circle = new google.maps.Circle({
        center: geolocation,
        radius: position.coords.accuracy
      });
      autocomplete.setBounds(circle.getBounds());
    });

  };

  // main
  initAutocomplete();

};


init = function (){
  $('input.gaddress-autocomplete').each( function(){
    gaComplete( $(this) );
  });
};


$.fn.gaddress = function (method)
{
    if ($.fn.gaddress[method])
    {
        return $.fn.gaddress[method].apply(this, Array.prototype.slice.call(arguments, 1));
    }
    else if (typeof method === "object" || !method)
    {
        return initialize.apply(this, arguments);
    }
    else
    {
        $.error("Method " + method + " does not exist on jQuery.gaddress");
    }
};

$.fn.gaddress.init = init;

})(jQuery);

$(document).gaddress('init');
</script>

<script type="text/javascript">

	// start jqueryform initialization
	// --------------------------------
	JF.init('#jqueryform-0a74c0');

</script>

  </body>
</html>